import Head from "next/head";
import Forms from "./components/forms/forms";
import styles from "@/styles/Home.module.css";
import Header from "./components/header";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="descripftion" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>

      <Header/>
      <Forms /> 
    </>
  );
}
